#!/usr/bin/env bun
/**
 * Fetches the latest LinkedIn posts from Apify and rewrites
 * src/config/linkedin-posts.ts with fresh data.
 *
 * Usage:
 *   APIFY_TOKEN=<token> APIFY_DATASET_ID=<datasetId> bun run scripts/refresh-linkedin-posts.ts
 *
 * The dataset ID is the one produced by the last run of the
 * harvestapi/linkedin-company-posts actor on the SIEAP account.
 * Update APIFY_DATASET_ID in the GitHub Actions secret whenever
 * you manually re-run the actor and get a new dataset.
 */

import { writeFileSync } from "fs";
import { join } from "path";

const TOKEN = process.env.APIFY_TOKEN;
const DATASET_ID = process.env.APIFY_DATASET_ID;

if (!TOKEN || !DATASET_ID) {
  console.error("APIFY_TOKEN and APIFY_DATASET_ID must be set.");
  process.exit(1);
}

const fields = "id,linkedinUrl,content,postedAt,postImages,engagement";
const url = `https://api.apify.com/v2/datasets/${DATASET_ID}/items?token=${TOKEN}&fields=${fields}&limit=100`;

console.log("Fetching posts from Apify dataset", DATASET_ID, "...");
const res = await fetch(url);
if (!res.ok) {
  console.error("Apify API error:", res.status, await res.text());
  process.exit(1);
}

const items = (await res.json()) as Array<{
  id: string;
  linkedinUrl: string;
  content: string;
  postedAt: { timestamp: number; date: string };
  postImages?: { url: string; width: number; height: number; expiresAt: number }[];
  engagement: { likes: number; comments: number; shares: number };
}>;

console.log(`Fetched ${items.length} posts.`);

const today = new Date().toISOString().slice(0, 10);
const latestId = items[0]?.id ?? "";

function esc(s: string): string {
  // escape backslashes then double-quotes, keep real newlines as \n literals
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function renderPost(p: (typeof items)[0]): string {
  const images = p.postImages
    ? `[{ url: "${esc(p.postImages[0].url)}", width: ${p.postImages[0].width}, height: ${p.postImages[0].height}, expiresAt: ${p.postImages[0].expiresAt} }]`
    : "undefined";

  return `  {
    id: "${p.id}",
    linkedinUrl: "${esc(p.linkedinUrl)}",
    content: "${esc(p.content)}",
    postedAt: { timestamp: ${p.postedAt.timestamp}, date: "${p.postedAt.date}" },
    postImages: ${images},
    engagement: { likes: ${p.engagement.likes}, comments: ${p.engagement.comments}, shares: ${p.engagement.shares} },
  }`;
}

const body = `export interface LinkedInPost {
  id: string;
  linkedinUrl: string;
  content: string;
  postedAt: { timestamp: number; date: string };
  postImages?: { url: string; width: number; height: number; expiresAt: number }[];
  engagement: { likes: number; comments: number; shares: number };
}

// Auto-generated by scripts/refresh-linkedin-posts.ts — do not edit by hand.
// Last synced: ${today}  |  Source: Apify dataset ${DATASET_ID}
export const LINKEDIN_POSTS_SEED: LinkedInPost[] = [
${items.map(renderPost).join(",\n")}
];

export const SEED_LATEST_ID = LINKEDIN_POSTS_SEED[0]?.id ?? "";
export const SEED_FETCH_DATE = "${today}";
`;

const outPath = join(import.meta.dir, "..", "src", "config", "linkedin-posts.ts");
writeFileSync(outPath, body, "utf8");
console.log("Written to", outPath);
