#!/usr/bin/env bun
/**
 * Fetches fresh LinkedIn posts from Apify and rewrites
 * src/config/linkedin-posts.ts with the new data.
 *
 * Supports two modes:
 *   1. Actor/Task mode (preferred — always fresh):
 *      APIFY_TOKEN=<token> APIFY_ACTOR_ID=<actorOrTaskId> bun run scripts/refresh-linkedin-posts.ts
 *      Triggers a synchronous actor run and returns the new dataset items.
 *
 *   2. Dataset mode (legacy — reads a fixed snapshot):
 *      APIFY_TOKEN=<token> APIFY_DATASET_ID=<datasetId> bun run scripts/refresh-linkedin-posts.ts
 *      Reads items from an existing dataset without running the actor.
 *
 * APIFY_ACTOR_ID can be the actor ID (e.g. "harvestapi~linkedin-company-posts")
 * or a task ID. Find it in Apify Console → your actor/task → API tab.
 */

import { writeFileSync } from "fs";
import { join } from "path";

const TOKEN = process.env.APIFY_TOKEN;
const ACTOR_ID = process.env.APIFY_ACTOR_ID;
const DATASET_ID = process.env.APIFY_DATASET_ID;

if (!TOKEN) {
  console.error("APIFY_TOKEN must be set.");
  process.exit(1);
}

if (!ACTOR_ID && !DATASET_ID) {
  console.error("Set either APIFY_ACTOR_ID (recommended) or APIFY_DATASET_ID.");
  process.exit(1);
}

const fields = "id,linkedinUrl,content,postedAt,postImages,engagement";
let items: Array<{
  id: string;
  linkedinUrl: string;
  content: string;
  postedAt: { timestamp: number; date: string };
  postImages?: { url: string; width: number; height: number; expiresAt: number }[];
  engagement: { likes: number; comments: number; shares: number };
}>;

if (ACTOR_ID) {
  // Run the actor synchronously and get items in one call (waits up to 300s)
  const runUrl =
    `https://api.apify.com/v2/acts/${ACTOR_ID}/run-sync-get-dataset-items` +
    `?token=${TOKEN}&fields=${fields}&limit=100&waitSecs=300`;
  console.log(`Triggering Apify actor ${ACTOR_ID} — waiting for results (up to 5 min)...`);
  const res = await fetch(runUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({}),
  });
  if (!res.ok) {
    console.error("Apify run-sync error:", res.status, await res.text());
    process.exit(1);
  }
  items = await res.json();
} else {
  // Read from the fixed dataset snapshot
  const url = `https://api.apify.com/v2/datasets/${DATASET_ID}/items?token=${TOKEN}&fields=${fields}&limit=100`;
  console.log(`Fetching posts from Apify dataset ${DATASET_ID}...`);
  const res = await fetch(url);
  if (!res.ok) {
    console.error("Apify API error:", res.status, await res.text());
    process.exit(1);
  }
  items = await res.json();
}

console.log(`Fetched ${items.length} posts.`);

if (items.length === 0) {
  console.error("Apify returned 0 items — aborting to avoid wiping the seed file.");
  process.exit(1);
}

const today = new Date().toISOString().slice(0, 10);
const source = ACTOR_ID ? `Apify actor ${ACTOR_ID}` : `Apify dataset ${DATASET_ID}`;

function esc(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}

function renderPost(p: (typeof items)[0]): string {
  const images =
    p.postImages && p.postImages.length > 0
      ? `[{ url: "${esc(p.postImages[0].url)}", width: ${p.postImages[0].width}, height: ${p.postImages[0].height}, expiresAt: ${p.postImages[0].expiresAt} }]`
      : "undefined";

  return `  {
    id: "${p.id}",
    linkedinUrl: "${esc(p.linkedinUrl)}",
    content: "${esc(p.content)}",
    postedAt: { timestamp: ${p.postedAt.timestamp}, date: "${p.postedAt.date}" },
    postImages: ${images},
    engagement: { likes: ${p.engagement.likes}, comments: ${p.engagement.comments}, shares: ${p.engagement.shares} },
  }`;
}

const body = `export interface LinkedInPost {
  id: string;
  linkedinUrl: string;
  content: string;
  postedAt: { timestamp: number; date: string };
  postImages?: { url: string; width: number; height: number; expiresAt: number }[];
  engagement: { likes: number; comments: number; shares: number };
}

// Auto-generated by scripts/refresh-linkedin-posts.ts — do not edit by hand.
// Last synced: ${today}  |  Source: ${source}
export const LINKEDIN_POSTS_SEED: LinkedInPost[] = [
${items.map(renderPost).join(",\n")}
];

export const SEED_LATEST_ID = LINKEDIN_POSTS_SEED[0]?.id ?? "";
export const SEED_FETCH_DATE = "${today}";
`;

const outPath = join(import.meta.dir, "..", "src", "config", "linkedin-posts.ts");
writeFileSync(outPath, body, "utf8");
console.log("Written to", outPath);
